const returnReasons={
  changed:"Change of mind",
  defective:"Defective item",
  damaged:"Damaged item",
  wrong:"Wrong item received",
  described:"Item not as described",
  other:"Other"
};
function findReturnOrder(){
  const no=qs("#returnOrder").value.trim().toUpperCase();
  const result=qs("#returnLookupResult");
  if(!no){result.innerHTML='<div class="alert">Please enter your order number to continue.</div>';return;}
  const order=NORTHSTAR_DEMO.orders[no];
  if(!order){result.innerHTML='<div class="alert"><strong>Order not found.</strong><br>Check the order number and try again.</div>';return;}
  localStorage.setItem("nsReturnOrder",no);
  qs("#orderSummary").innerHTML=`<div class="success"><strong>Order found.</strong><br>${esc(no)} — ${esc(order.item)}, size ${esc(order.size)}, quantity ${order.quantity}.</div>`;
  show("reasonSection"); hide("returnLookup");
}
function startReturn(){
  const reason=qs('input[name="returnReason"]:checked');
  const no=localStorage.getItem("nsReturnOrder");
  const result=qs("#eligibilityResult");
  if(!reason){result.innerHTML='<div class="alert">Please select a return reason.</div>';return;}
  const order=NORTHSTAR_DEMO.orders[no];
  if(!order){location.href="returns.html";return;}
  localStorage.setItem("nsReturnReason",reason.value);
  if(!order.returnEligible){
    result.innerHTML=`<div class="warning"><h2>Outside the Standard Return Period</h2>
    <p>According to the demonstration policy, this order falls outside the standard return period.</p>
    <p><strong>Permitted window:</strong> Returns for eligible items must be initiated within ${NORTHSTAR_DEMO.policy.returnWindowDays} days of the recorded delivery date.</p>
    <p><strong>What this means:</strong> The standard automated return pathway cannot be used because the recorded delivery date is outside the permitted window.</p>
    <p>You may still request human review if you believe there is an exception, such as a defective, damaged or incorrectly supplied item.</p></div>
    <div class="actions"><a class="button" href="human-support.html?order=${encodeURIComponent(no)}">Request Human Review</a><a class="button secondary" href="../index.html">Return to Support</a></div>`;
    show("eligibilitySection");return;
  }
  let extra="";
  if(reason.value==="defective") extra="<p><strong>Evidence:</strong> Be prepared to provide a clear description and demonstration image of the defect.</p>";
  if(reason.value==="damaged") extra="<p><strong>Evidence:</strong> Keep the product and packaging available and provide images showing the damage.</p>";
  if(reason.value==="wrong") extra="<p><strong>Verification:</strong> Keep the incorrect item and packaging available while the return request is processed.</p>";
  result.innerHTML=`<div class="success"><h2>Return Eligible</h2>
  <p>Your order is within the standard demonstration return period and can proceed through the return workflow.</p>
  <p><strong>Reason:</strong> ${esc(returnReasons[reason.value])}</p>
  ${extra}
  <h3>What you will need</h3>
  <ul><li>Order number</li><li>Product being returned</li><li>Suitable packaging</li><li>Return reference generated by this system</li></ul>
  <div class="actions"><a class="button" href="return-instructions.html">Continue to Return Instructions</a><a class="button secondary" href="../index.html">Return to Support</a></div></div>`;
  show("eligibilitySection");
}
function createReturn(){
  const no=localStorage.getItem("nsReturnOrder"), reason=localStorage.getItem("nsReturnReason")||"other";
  const ref=makeRef("RET");
  save("nsReturn",{reference:ref,order:no,reason:reason,status:"Return Request Created",created:new Date().toLocaleDateString()});
  location.href="return-status.html";
}